+incdir+/root/Project/u_core_top_soc/rtl
+incdir+/root/Project/u_core_dv_dma/agent
+incdir+/root/Project/u_core_dv_dma/env
+incdir+/root/Project/u_core_dv_dma/seq
+incdir+/root/Project/u_core_dv_dma/test
+incdir+/root/Project/u_core_dv_dma/tb
/root/Project/u_core_top_soc/rtl/u_core_pkg.sv
/root/Project/u_core_module_dma/rtl/dma_desc_stage.sv
/root/Project/u_core_module_dma/rtl/dma_desc_fifo.sv
/root/Project/u_core_module_dma/rtl/dma_addr_gen.sv
/root/Project/u_core_module_dma/rtl/dma_scheduler.sv
/root/Project/u_core_module_dma/rtl/dma_rd_engine.sv
/root/Project/u_core_module_dma/rtl/dma_wr_engine.sv
/root/Project/u_core_module_dma/rtl/dma_local_if.sv
/root/Project/u_core_module_dma/rtl/dma_status_perf.sv
/root/Project/u_core_module_dma/rtl/dma_csr_if.sv
/root/Project/u_core_module_dma/rtl/dma_top.sv
/root/Project/u_core_dv_dma/tb/dma_axil_if.sv
/root/Project/u_core_dv_dma/tb/dma_axi_mem_if.sv
/root/Project/u_core_dv_dma/tb/dma_spm_if.sv
/root/Project/u_core_dv_dma/tb/dma_status_if.sv
/root/Project/u_core_dv_dma/tb/dma_dv_pkg.sv
/root/Project/u_core_dv_dma/tb/dma_tb_top.sv
